FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY . .

RUN uv sync

EXPOSE 8082

CMD ["uv", "run", "uvicorn", "temporial_graph_rag.api.main:app", "--host", "0.0.0.0", "--port", "8082"]
